-- create_tables.sql
-- Run this in your 'research_lab' (or lab_manager) database.
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PUBLISHES;
DROP TABLE IF EXISTS PUBLICATION;
DROP TABLE IF EXISTS USES;
DROP TABLE IF EXISTS EQUIPMENT;
DROP TABLE IF EXISTS FUNDS;
DROP TABLE IF EXISTS WORKS;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS COLLABORATOR;
DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS LAB_MEMBER;
DROP TABLE IF EXISTS GRANT_TABLE;

SET FOREIGN_KEY_CHECKS = 1;

-- 1) GRANT (renamed GRANT_TABLE to avoid reserved keyword conflict)
CREATE TABLE GRANT_TABLE (
  GID INT PRIMARY KEY AUTO_INCREMENT,
  SOURCE VARCHAR(100),
  BUDGET DECIMAL(15,2),
  STARTDATE DATE,
  DURATION INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2) LAB_MEMBER
CREATE TABLE LAB_MEMBER (
  MID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(150) NOT NULL,
  JOINDATE DATE,
  MTYPE ENUM('Student','Faculty','Collaborator') DEFAULT 'Student',
  MENTOR INT NULL,
  CONSTRAINT fk_labmember_mentor FOREIGN KEY (MENTOR) REFERENCES LAB_MEMBER(MID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3) STUDENT (specialization)
CREATE TABLE STUDENT (
  MID INT PRIMARY KEY,
  SID INT UNIQUE,
  LEVEL VARCHAR(50),
  MAJOR VARCHAR(100),
  CONSTRAINT fk_student_member FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4) FACULTY
CREATE TABLE FACULTY (
  MID INT PRIMARY KEY,
  DEPARTMENT VARCHAR(100),
  CONSTRAINT fk_faculty_member FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5) COLLABORATOR
CREATE TABLE COLLABORATOR (
  MID INT PRIMARY KEY,
  AFFILIATION VARCHAR(200),
  BIOGRAPHY TEXT,
  CONSTRAINT fk_collab_member FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6) PROJECT
CREATE TABLE PROJECT (
  PID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(250),
  SDATE DATE,
  EDATE DATE,
  EDURATION INT,
  LEADER INT NULL,
  CONSTRAINT fk_project_leader FOREIGN KEY (LEADER) REFERENCES LAB_MEMBER(MID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7) WORKS (association)
CREATE TABLE WORKS (
  PID INT NOT NULL,
  MID INT NOT NULL,
  ROLE VARCHAR(100),
  HOURS INT,
  PRIMARY KEY (PID, MID),
  CONSTRAINT fk_works_project FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE,
  CONSTRAINT fk_works_member FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8) FUNDS (grant -> project)
CREATE TABLE FUNDS (
  GID INT NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (GID, PID),
  CONSTRAINT fk_funds_grant FOREIGN KEY (GID) REFERENCES GRANT_TABLE(GID) ON DELETE CASCADE,
  CONSTRAINT fk_funds_project FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9) EQUIPMENT
CREATE TABLE EQUIPMENT (
  EID INT PRIMARY KEY AUTO_INCREMENT,
  ENAME VARCHAR(200),
  ETYPE VARCHAR(100),
  STATUS VARCHAR(40),
  PDATE DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10) USES (equipment usage)
CREATE TABLE USES (
  MID INT NOT NULL,
  EID INT NOT NULL,
  SDATE DATETIME NOT NULL,
  EDATE DATETIME NULL,
  PURPOSE TEXT,
  PRIMARY KEY (MID, EID, SDATE),
  CONSTRAINT fk_uses_member FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE,
  CONSTRAINT fk_uses_equipment FOREIGN KEY (EID) REFERENCES EQUIPMENT(EID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11) PUBLICATION
CREATE TABLE PUBLICATION (
  PID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(500),
  VENUE VARCHAR(200),
  DATE DATE,
  DOI VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12) PUBLISHES (member -> publication)
CREATE TABLE PUBLISHES (
  MID INT NOT NULL,
  PID INT NOT NULL,
  SDATE DATE,
  EDATE DATE,
  PURPOSE TEXT,
  PRIMARY KEY (MID, PID),
  CONSTRAINT fk_publ_member FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE,
  CONSTRAINT fk_publ_pub FOREIGN KEY (PID) REFERENCES PUBLICATION(PID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13) Mentorship explicit (optional duplicate of MENTOR in LAB_MEMBER)
CREATE TABLE MENTORS (
  MENTOR INT NOT NULL,
  MENTEE INT NOT NULL,
  PROJECT_ID INT NULL,
  STARTDATE DATE,
  ENDDATE DATE,
  PRIMARY KEY (MENTOR, MENTEE),
  CONSTRAINT fk_mentors_mentor FOREIGN KEY (MENTOR) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE,
  CONSTRAINT fk_mentors_mentee FOREIGN KEY (MENTEE) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE,
  CONSTRAINT fk_mentors_project FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
